### ISSUE TITLE
Bug with "overwrite=True" in the write(). Error: _filename not defined 

### ISSUE THREAD

**Issue by matttheus** [plangrid/pdf-annotate#60]

**Comment by brandon-vidoori** [comment]
Looks like the private variable was omitted from [PdfAnnotator class](https://github.com/plangrid/pdf-annotate/blob/e78638d71f156ed79e8384e3bac54d638136211c/pdf_annotate/annotator.py#L68).

I believe it needs to be included roughly here (lines 84-87 _annotator.py_):
```
84        self._pdf = PDF(file_or_reader)
85        self._scale = self._expand_scale(scale)
86        self._dimensions = {}
87        self._compress = compress
```

**Comment by matttheus** [comment]
Thanks, it works
